### ISSUE TITLE
Bastion host shouldn't work as gateway

### ISSUE THREAD

**Issue by nohant** [sighupio/fury-kubernetes-openvpn#3]
Hello,

We would like to have the default setting of the VPN not to handle all the traffic but just the ones which are coming to VPN'S related domain.
in this way we could also switch from staging to production VPN without disconnecting every time, making debugging and working easier and less frustrating

Something like:
www.youtube.com shouldn’t go through OpenVPN
app.k8s.cluster.fury will pass trough the Bastion

**Comment by lnovara** [comment]
Yes, this is totally reasonable but you'll have to make sure that you're able to resolve all the "private" DNS records that you need while you're connected to both VPNs.

**Comment by nohant** [comment]
sorry, I thought this was inside the bastion configuration and not client-side.
you need something from the client?

**Comment by lnovara** [comment]
@nohant, whenever you connect to an OpenVPN server configured with this Ansible role, the server will push the DNS config to your client.

If you want to connect to more than one OpenVPN server at a time (which is a reasonable thing to do), you will have to manage the DNS configuration with something like https://github.com/jonathanio/update-systemd-resolved. Unfortunately, I am not aware of something similar that works on macOS.
